### Numpy 기초
- 수치해석 , 수학적 계산 목적으로한 라이브러리. 수치해석 최대화

### Numpy 설치
```shell
!pip install [update] numpy
```

In [74]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [75]:
!pip install update numpy


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


- Numpy사용

In [76]:
import numpy as np # 보통 np로 줄여서 사용

In [77]:
lst=[1,2,3,4] #리스트

In [78]:
# 1차원 배열 생성
arr = np.array(lst)
arr #numpy 배열

array([1, 2, 3, 4])

In [79]:
# 배열의 구조
arr.shape # 1차원 배열 , 크기 4

(4,)

In [80]:
# 2차원 배열
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
# arr2 구조
arr2.shape # 2차원 배열 , 2행 4열 

(2, 4)

In [82]:
# 2차원 배열 , 1행 4열짜리
arr3 = np.array([[1,2,3,4]])
arr3.shape

(1, 4)

In [83]:
# 3차원 배열, 사용할 일 거의 거의 없음
arr4 = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]],
                 [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]])
arr4.shape

(2, 4, 4)

In [84]:
#넘파이 데이터타입 확인
arr3.dtype

dtype('int32')

- 넘파이 자료형   
    - 부호 정수 : int8, int16, int32, int64
    - 무부호 정소 : uint8, uint16, uint32, uint64
    - 실수 : float8, float16, float32, float64
    - 복소수 : complex8, complex16, complex32, complex64
    - 문자열 : string_
    - 불링 : bool
    - 유니코드 : unicode_
    - 파이썬오브젝트 : object

- 넘파이 배열 정의

In [85]:
# 1차원 요소 10개가 모두 0인 배열 초기화
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
# 2차원 배열, 2행 4열 모두가 0인 배열 초기화
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
# 1차원 요소 10개를 모두 1로 배열 초기화
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [88]:
#2차원 배열, 2행 4열 모두가 1로 초기화
np.ones((2, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [89]:
# 3부터 1씩 증가, 9가 마지막인 배열 초기화
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [90]:
# 3부터 2씩 증가, 9가 마지막인 배열 초기화
np.arange(3, 10 ,2)

array([3, 5, 7, 9])

- 사용하는 이유

In [91]:
## 대용량리스트(1억) 생성
pyList = list(range(10_000_000))
npList = np.arange(10_100_000)

In [92]:
len(pyList) #리스트 길이

10000000

In [93]:
npList.shape

(10100000,)

In [94]:
## 파이썬 리스트 계산처리 시간
%timeit for _ in range(10) : pyList2 = pyList  * 2

2.29 s ± 322 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [95]:
## 넘파이 배열 계산처리 시간
%timeit for _ in range(10): npList2 = npList * 2

156 ms ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


- 넘파이로 수치계산을 하면 시간을 절약

In [ ]:
!pip install